"""
pr_bot.py — Posts a risk-score comment on GitHub/GitLab PRs/MRs.

Usage:
    python pr_bot.py --platform github --repo owner/repo --pr 42 --score 0.72 --recommendation hold

Or import and call post_github_comment() / post_gitlab_comment() directly
from webhook_handler.py after receiving an event.

Environment variables:
    GITHUB_TOKEN  — Personal access token with repo scope
    GITLAB_TOKEN  — Personal access token with api scope
    GITLAB_URL    — GitLab instance URL (default: https://gitlab.com)
"""

import os
import httpx
import argparse

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITLAB_TOKEN = os.getenv("GITLAB_TOKEN", "")
GITLAB_URL   = os.getenv("GITLAB_URL", "https://gitlab.com")


# ── Comment builders ───────────────────────────────────────────────────────────

def build_comment(score: float, recommendation: str, risk_factors: list[str], service: str) -> str:
    """Builds a formatted markdown comment for the PR/MR."""
    emoji = {"proceed": "✅", "review": "⚠️", "hold": "🚫"}.get(recommendation, "ℹ️")
    bar   = build_score_bar(score)

    factors_md = "\n".join(f"- {f}" for f in risk_factors) if risk_factors else "- No risk factors identified"

    return f"""## {emoji} DevOps Pipeline Agent — Risk Assessment

**Service:** `{service}`
**Risk Score:** `{score:.2f}` {bar}
**Recommendation:** `{recommendation.upper()}`

### Risk Factors
{factors_md}

---
<sub>🤖 Generated by [devops-pipeline-agent](https://gitlab.com/vaishnavisampeta90/devops-pipeline-agent) · 
Score range: 0.0 (safe) → 1.0 (high risk) · 
Hold if ≥ 0.7, Review if ≥ 0.4, Proceed otherwise</sub>
"""


def build_score_bar(score: float) -> str:
    """Simple ASCII progress bar for the risk score."""
    filled = int(score * 10)
    empty  = 10 - filled
    color  = "🔴" if score >= 0.7 else "🟡" if score >= 0.4 else "🟢"
    return f"{color} `{'█' * filled}{'░' * empty}` {int(score * 100)}%"


# ── GitHub ─────────────────────────────────────────────────────────────────────

def post_github_comment(repo: str, pr_number: int, comment: str) -> bool:
    """
    Posts a comment on a GitHub Pull Request.
    repo format: "owner/repo-name"
    """
    if not GITHUB_TOKEN:
        print("[WARN] GITHUB_TOKEN not set — skipping GitHub comment")
        return False

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    response = httpx.post(url, json={"body": comment}, headers=headers, timeout=10.0)

    if response.status_code == 201:
        print(f"[PR BOT] Comment posted on GitHub PR #{pr_number}")
        return True
    else:
        print(f"[ERROR] GitHub comment failed: {response.status_code} — {response.text}")
        return False


def delete_previous_bot_comments(repo: str, pr_number: int):
    """Removes old bot comments so the PR doesn't get cluttered on each push."""
    if not GITHUB_TOKEN:
        return

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }

    response = httpx.get(url, headers=headers, timeout=10.0)
    if response.status_code != 200:
        return

    for comment in response.json():
        if "DevOps Pipeline Agent" in comment.get("body", ""):
            delete_url = f"https://api.github.com/repos/{repo}/issues/comments/{comment['id']}"
            httpx.delete(delete_url, headers=headers, timeout=10.0)
            print(f"[PR BOT] Deleted old bot comment {comment['id']}")


# ── GitLab ─────────────────────────────────────────────────────────────────────

def post_gitlab_comment(project_id: str, mr_iid: int, comment: str) -> bool:
    """
    Posts a note on a GitLab Merge Request.
    project_id: numeric ID or "namespace/project" (URL-encoded)
    """
    if not GITLAB_TOKEN:
        print("[WARN] GITLAB_TOKEN not set — skipping GitLab comment")
        return False

    import urllib.parse
    encoded_project = urllib.parse.quote(project_id, safe="")
    url = f"{GITLAB_URL}/api/v4/projects/{encoded_project}/merge_requests/{mr_iid}/notes"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}

    response = httpx.post(url, json={"body": comment}, headers=headers, timeout=10.0)

    if response.status_code == 201:
        print(f"[PR BOT] Note posted on GitLab MR !{mr_iid}")
        return True
    else:
        print(f"[ERROR] GitLab note failed: {response.status_code} — {response.text}")
        return False


# ── High-level helper ──────────────────────────────────────────────────────────

def comment_risk_score(
    platform: str,
    repo_or_project: str,
    pr_number: int,
    assessment: dict,
    service: str,
):
    """
    Single entry point called from webhook_handler after risk scoring.

    platform: "github" | "gitlab"
    assessment: dict with keys score, recommendation, risk_factors
    """
    comment = build_comment(
        score=assessment.get("score", 0.0),
        recommendation=assessment.get("recommendation", "proceed"),
        risk_factors=assessment.get("risk_factors", []),
        service=service,
    )

    if platform == "github":
        delete_previous_bot_comments(repo_or_project, pr_number)
        post_github_comment(repo_or_project, pr_number, comment)
    elif platform == "gitlab":
        post_gitlab_comment(repo_or_project, pr_number, comment)
    else:
        print(f"[WARN] Unknown platform: {platform}")


# ── CLI entry point ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Post a risk score comment on a PR/MR")
    parser.add_argument("--platform", choices=["github", "gitlab"], required=True)
    parser.add_argument("--repo",     required=True, help="owner/repo or project path")
    parser.add_argument("--pr",       type=int,      required=True, help="PR/MR number")
    parser.add_argument("--service",  default="unknown")
    parser.add_argument("--score",    type=float,    default=0.5)
    parser.add_argument("--recommendation", default="review")
    parser.add_argument("--factors",  nargs="*",     default=[])
    args = parser.parse_args()

    comment_risk_score(
        platform=args.platform,
        repo_or_project=args.repo,
        pr_number=args.pr,
        assessment={
            "score": args.score,
            "recommendation": args.recommendation,
            "risk_factors": args.factors,
        },
        service=args.service,
    )
